### ISSUE TITLE
Demos

### ISSUE THREAD

**Issue by deini** [happyCoda/vue-notifikation#8]
Would be really helpful if you can add some demos to the README or setup a playground website.

**Comment by happyCoda** [comment]
Hi, @deini! There is an example directory inside repo, and if you run gulp dev and open your localhost on port 3000, you will see a demo.

**Comment by deini** [comment]
Thanks @happyCoda that definitely works, I would still recommend some demo site / screenshots in the Readme as it would make life easier for people looking for a notifications library and considering multiple repos.
